apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-mysql-secret
              key: DB_USERNAME     
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-mysql-secret
              key: DB_PASSWORD