apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-pvc
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: ejemplo-almacenamiento
  volumes:
    - name: ejemplo-almacenamiento
      persistentVolumeClaim:
        claimName: pvc-ejemplo