apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzcw==
  #DB_HOST: ZGI=
  #DB_NAME: Zmxhc2thcHA=

---

apiVersion: v1
kind: Secret
metadata:
  name: flaskapp-secret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzcw==
  DB_HOST: ZGI=
  DB_NAME: Zmxhc2thcHA=

