apiVersion: v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
  spec:
    containers:
      - name: flask-App
        image: facumiglio/flaskapp:${IMAGE_TAG}
        ports:
          - containerPort: 5000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flaskapp-secret
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: flaskapp-secret
                key: DB_USER
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: flaskapp-secret
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: flaskapp-secret
                key: DB_HOST                

